### ISSUE TITLE
cannot find -lnvidia-ml

### ISSUE THREAD

**Issue by zappityzap** [ThomasBaruzier/gddr6-core-junction-vram-temps#1]
I had some trouble compiling on Ubuntu 22.04:

```
$ gcc gputemps.c -o gputemps -O3 -lnvidia-ml -lpci
/usr/bin/ld: cannot find -lnvidia-ml: No such file or directory
collect2: error: ld returned 1 exit status
```

Not sure if this is correct but it worked:
```
$ gcc gputemps.c -o gputemps -O3 -lnvidia-ml -lpci -L/usr/local/cuda-12.6/targets/x86_64-linux/lib/stubs/
```

I found the path with `find /usr /lib /opt -name "libnvidia-ml.so*"`

**Comment by ThomasBaruzier** [comment]
Hi, you probably haven't installed `nvidia-cuda-toolkit` ([readme](https://github.com/ThomasBaruzier/gddr6-core-junction-vram-temps?tab=readme-ov-file#dependencies))

If you did and you still have issues, you can try using `./build-docker.sh`

**Comment by zappityzap** [comment]
Apparently I have all the cuda-toolkits installed. `nvidia-cuda-toolkit` seems to pull 11.5 from Ubuntu repos, while nvidia uses `cuda-toolkit` for their repos. Oh well, docker build worked too. thanks.

```
cuda-toolkit-12-5-config-common/unknown,now 12.5.82-1 all [installed,automatic]
cuda-toolkit-12-5/unknown,now 12.5.1-1 amd64 [installed]
cuda-toolkit-12-6-config-common/unknown,now 12.6.77-1 all [installed,automatic]
cuda-toolkit-12-6/unknown,now 12.6.3-1 amd64 [installed,automatic]
cuda-toolkit-12-config-common/unknown,now 12.6.77-1 all [installed,automatic]
cuda-toolkit-config-common/unknown,now 12.6.77-1 all [installed,automatic]
cuda-toolkit/unknown,now 12.6.3-1 amd64 [installed]
nvidia-cuda-toolkit-doc/jammy,now 11.5.1-1ubuntu1 all [installed,automatic]
nvidia-cuda-toolkit/jammy,now 11.5.1-1ubuntu1 amd64 [installed]
```

**Comment by ThomasBaruzier** [comment]
Weird

I heard Ubuntu repos weren't up-to-date regarding cuda and other similar tools
Maybe mixing cuda components from 11.5 and 12.5 caused this error

If anyone stumbles upon this, try uninstalling and reinstalling cuda to its latest version, here's a guide: https://linuxconfig.org/how-to-install-cuda-on-ubuntu-20-04-focal-fossa-linux (2nd part)
Or just use the docker build method like zappityzap did.

Feel free to reopen if needed
